-- MySQL Script generated by MySQL Workbench
-- Fri 25 May 2018 10:48:53 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aredespacio` ;

-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aredespacio` DEFAULT CHARACTER SET utf8 ;
USE `aredespacio` ;

-- -----------------------------------------------------
-- Table `aredespacio`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`alumno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`alumno` (
  `idAlumno` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `imgFoto` VARCHAR(200) NULL DEFAULT NULL,
  `esActivo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`horario` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`horario` (
  `idHorario` INT(11) NOT NULL,
  `rutaArchivo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`usuario` (
  `nombreUsuario` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(20) NOT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`maestro` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`maestro` (
  `idMaestro` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `imgFoto` VARCHAR(200) NULL DEFAULT NULL,
  `esActivo` TINYINT(1) NULL DEFAULT '1',
  `esDirector` TINYINT(1) NULL DEFAULT '0',
  `usuario_nombreUsuario` VARCHAR(30) NOT NULL DEFAULT 'usuario',
  PRIMARY KEY (`idMaestro`, `usuario_nombreUsuario`),
  INDEX `fk_maestro_usuario1_idx` (`usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_maestro_usuario1`
    FOREIGN KEY (`usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`usuario` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`grupo` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`grupo` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` INT(11) NULL DEFAULT NULL,
  `fechaCreacion` DATE NULL DEFAULT NULL,
  `maestro_idMaestro` INT(11) NOT NULL,
  `maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  `horario_idHorario` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `tipoDanza` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupo`, `maestro_idMaestro`, `maestro_usuario_nombreUsuario`, `horario_idHorario`),
  INDEX `fk_grupo_maestro1_idx` (`maestro_idMaestro` ASC, `maestro_usuario_nombreUsuario` ASC),
  INDEX `fk_grupo_horario1_idx` (`horario_idHorario` ASC),
  CONSTRAINT `fk_grupo_horario1`
    FOREIGN KEY (`horario_idHorario`)
    REFERENCES `aredespacio`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_maestro1`
    FOREIGN KEY (`maestro_idMaestro` , `maestro_usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro` , `usuario_nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`asistencia` (
  `idasistencia` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `grupo_idGrupo` INT(11) NOT NULL,
  `grupo_maestro_idMaestro` INT(11) NOT NULL,
  `grupo_maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  `grupo_horario_idHorario` INT(11) NOT NULL,
  PRIMARY KEY (`idasistencia`, `grupo_idGrupo`, `grupo_maestro_idMaestro`, `grupo_maestro_usuario_nombreUsuario`, `grupo_horario_idHorario`),
  INDEX `fk_asistencia_grupo1_idx` (`grupo_idGrupo` ASC, `grupo_maestro_idMaestro` ASC, `grupo_maestro_usuario_nombreUsuario` ASC, `grupo_horario_idHorario` ASC),
  CONSTRAINT `fk_asistencia_grupo1`
    FOREIGN KEY (`grupo_idGrupo` , `grupo_maestro_idMaestro` , `grupo_maestro_usuario_nombreUsuario` , `grupo_horario_idHorario`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo` , `maestro_idMaestro` , `maestro_usuario_nombreUsuario` , `horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`cliente` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `imgFoto` VARCHAR(200) NULL DEFAULT NULL,
  `esActivo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`egreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`egreso` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`egreso` (
  `idEgreso` INT(11) NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(150) NOT NULL,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idEgreso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`grupo_has_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`grupo_has_alumno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`grupo_has_alumno` (
  `grupo_idGrupo` INT(11) NOT NULL,
  `grupo_maestro_idMaestro` INT(11) NOT NULL,
  `grupo_maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  `grupo_horario_idHorario` INT(11) NOT NULL,
  `alumno_idAlumno` INT(11) NOT NULL,
  PRIMARY KEY (`grupo_idGrupo`, `grupo_maestro_idMaestro`, `grupo_maestro_usuario_nombreUsuario`, `grupo_horario_idHorario`, `alumno_idAlumno`),
  INDEX `fk_grupo_has_alumno_alumno1_idx` (`alumno_idAlumno` ASC),
  INDEX `fk_grupo_has_alumno_grupo1_idx` (`grupo_idGrupo` ASC, `grupo_maestro_idMaestro` ASC, `grupo_maestro_usuario_nombreUsuario` ASC, `grupo_horario_idHorario` ASC),
  CONSTRAINT `fk_grupo_has_alumno_alumno1`
    FOREIGN KEY (`alumno_idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_alumno_grupo1`
    FOREIGN KEY (`grupo_idGrupo` , `grupo_maestro_idMaestro` , `grupo_maestro_usuario_nombreUsuario` , `grupo_horario_idHorario`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo` , `maestro_idMaestro` , `maestro_usuario_nombreUsuario` , `horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`promocion` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`promocion` (
  `idPromocion` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `concepto` VARCHAR(100) NULL DEFAULT NULL,
  `descuento` INT(11) NOT NULL,
  `paraInscripcion` TINYINT NULL DEFAULT 1,
  `maestro_idMaestro` INT(11) NOT NULL,
  `maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPromocion`, `maestro_idMaestro`, `maestro_usuario_nombreUsuario`),
  INDEX `fk_promocion_maestro1_idx` (`maestro_idMaestro` ASC, `maestro_usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_promocion_maestro1`
    FOREIGN KEY (`maestro_idMaestro` , `maestro_usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro` , `usuario_nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoAlumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoAlumno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoAlumno` (
  `idPagoAlumno` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fechaPago` DATE NULL DEFAULT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `plazo` INT(11) NULL DEFAULT NULL,
  `alumno_idAlumno` INT(11) NOT NULL,
  `promocion_idPromocion` INT(11) NULL DEFAULT NULL,
  `promocion_maestro_idMaestro` INT(11) NULL DEFAULT NULL,
  `promocion_maestro_usuario_nombreUsuario` VARCHAR(30) NULL,
  `grupo_idGrupo` INT(11) NOT NULL,
  `grupo_maestro_idMaestro` INT(11) NOT NULL,
  `grupo_maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  `grupo_horario_idHorario` INT(11) NOT NULL,
  PRIMARY KEY (`idPagoAlumno`, `alumno_idAlumno`, `grupo_idGrupo`, `grupo_maestro_idMaestro`, `grupo_maestro_usuario_nombreUsuario`, `grupo_horario_idHorario`),
  INDEX `fk_pagoAlumno_alumno1_idx` (`alumno_idAlumno` ASC),
  INDEX `fk_pagoAlumno_promocion1_idx` (`promocion_idPromocion` ASC, `promocion_maestro_idMaestro` ASC, `promocion_maestro_usuario_nombreUsuario` ASC),
  INDEX `fk_pagoAlumno_grupo1_idx` (`grupo_idGrupo` ASC, `grupo_maestro_idMaestro` ASC, `grupo_maestro_usuario_nombreUsuario` ASC, `grupo_horario_idHorario` ASC),
  CONSTRAINT `fk_pagoAlumno_alumno1`
    FOREIGN KEY (`alumno_idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagoAlumno_grupo1`
    FOREIGN KEY (`grupo_idGrupo` , `grupo_maestro_idMaestro` , `grupo_maestro_usuario_nombreUsuario` , `grupo_horario_idHorario`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo` , `maestro_idMaestro` , `maestro_usuario_nombreUsuario` , `horario_idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagoAlumno_promocion1`
    FOREIGN KEY (`promocion_idPromocion` , `promocion_maestro_idMaestro` , `promocion_maestro_usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`promocion` (`idPromocion` , `maestro_idMaestro` , `maestro_usuario_nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoAlumnoExterno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoAlumnoExterno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoAlumnoExterno` (
  `idPagoAlExterno` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `maestro_idMaestro` INT(11) NOT NULL,
  `maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  `alumno_idAlumno` INT(11) NOT NULL,
  PRIMARY KEY (`idPagoAlExterno`, `maestro_idMaestro`, `maestro_usuario_nombreUsuario`, `alumno_idAlumno`),
  INDEX `fk_pagoAlumnoExterno_maestro1_idx` (`maestro_idMaestro` ASC, `maestro_usuario_nombreUsuario` ASC),
  INDEX `fk_pagoAlumnoExterno_alumno1_idx` (`alumno_idAlumno` ASC),
  CONSTRAINT `fk_pagoAlumnoExterno_alumno1`
    FOREIGN KEY (`alumno_idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagoAlumnoExterno_maestro1`
    FOREIGN KEY (`maestro_idMaestro` , `maestro_usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro` , `usuario_nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoMaestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoMaestro` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoMaestro` (
  `idPagoMaestro` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `plazo` INT(11) NULL DEFAULT NULL,
  `fecha_vencimiento` DATE NULL,
  `maestro_idMaestro` INT(11) NOT NULL,
  `maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPagoMaestro`, `maestro_idMaestro`, `maestro_usuario_nombreUsuario`),
  INDEX `fk_pagoMaestro_maestro1_idx` (`maestro_idMaestro` ASC, `maestro_usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_pagoMaestro_maestro1`
    FOREIGN KEY (`maestro_idMaestro` , `maestro_usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro` , `usuario_nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoRenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoRenta` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoRenta` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `monto` DOUBLE NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`publicidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`publicidad` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`publicidad` (
  `idPublicidad` INT(11) NOT NULL,
  `Egreso_idEgreso` INT(11) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `monto` INT(11) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `maestro_idMaestro` INT(11) NOT NULL,
  `maestro_usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPublicidad`, `maestro_idMaestro`, `maestro_usuario_nombreUsuario`),
  INDEX `fk_Promoción_Egreso1_idx` (`Egreso_idEgreso` ASC),
  INDEX `fk_publicidad_maestro1_idx` (`maestro_idMaestro` ASC, `maestro_usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_Promoción_Egreso1`
    FOREIGN KEY (`Egreso_idEgreso`)
    REFERENCES `aredespacio`.`egreso` (`idEgreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicidad_maestro1`
    FOREIGN KEY (`maestro_idMaestro` , `maestro_usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro` , `usuario_nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `aredespacio`.`renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`renta` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`renta` (
  `idRenta` INT(11) NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT(11) NOT NULL,
  `pagoRenta_idPago` INT(11) NOT NULL,
  `horario_idHorario` INT(11) NOT NULL,
  PRIMARY KEY (`idRenta`, `Cliente_idCliente`, `pagoRenta_idPago`, `horario_idHorario`),
  INDEX `fk_Renta_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_renta_pagoRenta1_idx` (`pagoRenta_idPago` ASC),
  INDEX `fk_renta_horario1_idx` (`horario_idHorario` ASC),
  CONSTRAINT `fk_Renta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `aredespacio`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renta_horario1`
    FOREIGN KEY (`horario_idHorario`)
    REFERENCES `aredespacio`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_renta_pagoRenta1`
    FOREIGN KEY (`pagoRenta_idPago`)
    REFERENCES `aredespacio`.`pagoRenta` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
