-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 01:18:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `aredespacio` ;

-- -----------------------------------------------------
-- Schema aredespacio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aredespacio` DEFAULT CHARACTER SET utf8 ;
USE `aredespacio` ;

-- -----------------------------------------------------
-- Table `aredespacio`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`alumno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL,
  `imgFoto` VARCHAR(200) NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`usuario` (
  `nombreUsuario` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`maestro` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`maestro` (
  `idMaestro` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL,
  `imgFoto` VARCHAR(200) NULL,
  `usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idMaestro`, `usuario_nombreUsuario`),
  INDEX `fk_maestro_usuario1_idx` (`usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_maestro_usuario1`
    FOREIGN KEY (`usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`usuario` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`horario` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`horario` (
  `idHorario` INT NOT NULL,
  `rutaArchivo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`grupo` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `Maestro_idMaestro` INT NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  `estado` INT NULL,
  `fechaCreacion` DATE NULL,
  PRIMARY KEY (`idGrupo`, `Maestro_idMaestro`, `Horario_idHorario`),
  INDEX `fk_Grupo_Maestro1_idx` (`Maestro_idMaestro` ASC),
  INDEX `fk_Grupo_Horario1_idx` (`Horario_idHorario` ASC),
  CONSTRAINT `fk_Grupo_Maestro1`
    FOREIGN KEY (`Maestro_idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `aredespacio`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`director` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`director` (
  `idDirector` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL,
  `imgFoto` VARCHAR(200) NULL,
  `usuario_nombreUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idDirector`, `usuario_nombreUsuario`),
  INDEX `fk_director_usuario1_idx` (`usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_director_usuario1`
    FOREIGN KEY (`usuario_nombreUsuario`)
    REFERENCES `aredespacio`.`usuario` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoRenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoRenta` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoRenta` (
  `idPago` INT NOT NULL,
  `monto` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`cliente` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `email` VARCHAR(100) NULL,
  `imgFoto` VARCHAR(200) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`renta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`renta` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`renta` (
  `idRenta` INT NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Pago_idPago` INT NOT NULL,
  PRIMARY KEY (`idRenta`, `Horario_idHorario`, `Cliente_idCliente`, `Pago_idPago`),
  INDEX `fk_Renta_Horario1_idx` (`Horario_idHorario` ASC),
  INDEX `fk_Renta_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Renta_Pago1_idx` (`Pago_idPago` ASC),
  CONSTRAINT `fk_Renta_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `aredespacio`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Renta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `aredespacio`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Renta_Pago1`
    FOREIGN KEY (`Pago_idPago`)
    REFERENCES `aredespacio`.`pagoRenta` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`inscripcion` (
  `Alumno_idAlumno` INT NOT NULL,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`Alumno_idAlumno`, `Grupo_idGrupo`),
  INDEX `fk_Alumno_has_Grupo_Grupo1_idx` (`Grupo_idGrupo` ASC),
  INDEX `fk_Alumno_has_Grupo_Alumno_idx` (`Alumno_idAlumno` ASC),
  CONSTRAINT `fk_Alumno_has_Grupo_Alumno`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Grupo_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `aredespacio`.`grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`egreso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`egreso` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`egreso` (
  `idEgreso` INT NOT NULL,
  `concepto` VARCHAR(150) NOT NULL,
  `monto` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idEgreso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`publicidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`publicidad` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`publicidad` (
  `idPromoción` INT NOT NULL,
  `Egreso_idEgreso` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `monto` INT NOT NULL,
  `url` VARCHAR(255) NULL,
  `maestro_idMaestro` INT NOT NULL,
  PRIMARY KEY (`idPromoción`, `maestro_idMaestro`),
  INDEX `fk_Promoción_Egreso1_idx` (`Egreso_idEgreso` ASC),
  INDEX `fk_publicidad_maestro1_idx` (`maestro_idMaestro` ASC),
  CONSTRAINT `fk_Promoción_Egreso1`
    FOREIGN KEY (`Egreso_idEgreso`)
    REFERENCES `aredespacio`.`egreso` (`idEgreso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicidad_maestro1`
    FOREIGN KEY (`maestro_idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoMaestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoMaestro` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoMaestro` (
  `idPagoMaestro` INT NOT NULL,
  `Maestro_idMaestro` INT NOT NULL,
  `monto` INT NULL,
  `fecha` DATE NULL,
  `plazo` INT NULL,
  PRIMARY KEY (`idPagoMaestro`, `Maestro_idMaestro`),
  INDEX `fk_PagoMaestro_Maestro1_idx` (`Maestro_idMaestro` ASC),
  CONSTRAINT `fk_PagoMaestro_Maestro1`
    FOREIGN KEY (`Maestro_idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`promocion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`promocion` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`promocion` (
  `idPromoción` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `maestro_idMaestro` INT NOT NULL,
  `concepto` VARCHAR(100) NULL,
  `descuento` INT NOT NULL,
  PRIMARY KEY (`idPromoción`, `maestro_idMaestro`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_promocion_maestro1_idx` (`maestro_idMaestro` ASC),
  CONSTRAINT `fk_promocion_maestro1`
    FOREIGN KEY (`maestro_idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoAlumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoAlumno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoAlumno` (
  `idPagoAlumno` INT NOT NULL AUTO_INCREMENT,
  `Alumno_idAlumno` INT NOT NULL,
  `Promoción_idPromoción` INT NOT NULL,
  `monto` INT NOT NULL,
  `fechaPago` DATE NULL,
  `plazo` INT NULL,
  PRIMARY KEY (`idPagoAlumno`, `Alumno_idAlumno`),
  INDEX `fk_PagoAlumno_Alumno1_idx` (`Alumno_idAlumno` ASC),
  INDEX `fk_PagoAlumno_Promoción1_idx` (`Promoción_idPromoción` ASC),
  CONSTRAINT `fk_PagoAlumno_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PagoAlumno_Promoción1`
    FOREIGN KEY (`Promoción_idPromoción`)
    REFERENCES `aredespacio`.`promocion` (`idPromoción`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aredespacio`.`pagoAlumnoExterno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aredespacio`.`pagoAlumnoExterno` ;

CREATE TABLE IF NOT EXISTS `aredespacio`.`pagoAlumnoExterno` (
  `idPagoAlExterno` INT NOT NULL,
  `Maestro_idMaestro` INT NOT NULL,
  `Alumno_idAlumno` INT NOT NULL,
  `monto` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idPagoAlExterno`, `Maestro_idMaestro`, `Alumno_idAlumno`),
  INDEX `fk_PagoAlExterno_Maestro1_idx` (`Maestro_idMaestro` ASC),
  INDEX `fk_PagoAlExterno_Alumno1_idx` (`Alumno_idAlumno` ASC),
  CONSTRAINT `fk_PagoAlExterno_Maestro1`
    FOREIGN KEY (`Maestro_idMaestro`)
    REFERENCES `aredespacio`.`maestro` (`idMaestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PagoAlExterno_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `aredespacio`.`alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
